var IntroTextos = [
	"En la Institución Educativa el Limonar tenemos una estrategia de formación en la que docentes de la básica primaria, nos hemos dado a la tarea de diseñar guías de aprendizaje que favorecen conocimientos, habilidades y actitudes para que los niños aprendan a resolver dos necesidades básicas que son urgentes en tiempos de pandemia: El autocuidado desde la salud y la alimentación y la sana convivencia.",
	"En la Institución Educativa Nicanor Restrepo Santamaria todas las áreas se integran para trabajar bajo la premisa:  la <i>“Casa como Laboratorio”</i>, en esta iniciativa los estudiantes de los grados sexto y séptimo desarrollan su proceso formativo utilizando los implementos, lugares y recursos del hogar; de ahí la importancia de la participación de los padres de familia y la planeación de los docentes.",
	"En la Institución Educativa Caracas implementamos un proyecto de investigación documental que vincula estudiantes curiosos e interesados en la indagación. Buscamos fortalecer la integración del currículo entre la básica y la media, generar comprensiones respecto a la influencia que ha tenido el mar en el desarrollo de las civilizaciones y analizar el impacto en el desarrollo de los pueblos.",
	"En la Institución Educativa la Esperanza tenemos una iniciativa de cátedra de paz “narrándonos desde la memoria” que lleva cinco años en los cuales: el teatro, la música, el cine, el arte, la literatura y el trabajo académico, han permitido construir una narrativa frente a la construcción de paz y las memorias; asociadas al conflicto armado colombiano a la luz de las experiencias de las y los estudiantes.",
	"En la Institución Educativa Alfonso Upegui Orozco, tenemos un proyecto que tiene dentro de sus objetivos crear un jardín abierto para atraer diferentes especies de mariposas de la vereda Pajarito fortaleciendo a través de éste, el estudio y conservación de especies endémicas. Este proyecto, dirigido a la básica primaria, ha permitido consolidar en los últimos dos años habilidades investigativas y competencias ciudadanas en los estudiantes.",
	"En la Institución Educativa Arzobispo Tulio Botero Salazar, implementamos una experiencia para desarrollar competencias investigativas en los estudiantes a través de la experimentación y la integración curricular. Permite dar solución a problemas cotidianos, conectado con situaciones de matemáticas, ciencias naturales, convivencia, entorno social y familiar. Apoyados de las TIC y del pensamiento creativo. Está dirigida a toda la primaria.",
	"En la Institución Educativa Colegio Loyola estamos implementando hace 10 años, una estrategia educativa que está dirigida a todos los estudiantes en articulación con el Sena.  En la iniciativa se exploran las líneas de investigación: nanotecnología, ciencias básicas, ingeniería, electrónica - robótica, diseño - prototipado y biotecnología. Formamos en nociones de investigación escolar, asesorando los proyectos desde el modelo de trabajo colaborativo."
];
